### ISSUE TITLE
Movement crawls to a hault when items are spawned near JanusWeb avatars

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#134] opened 2018-04-21 20:06 UTC
After testing with ghosts and people who are world building while a JanusWeb user observes I noticed that on the janusweb user side their movement becomes severely throttled even when the objects are spawned far away. Tested with current and 1.2.

**Comment by jbaicoianu** [comment] 2021-11-03 23:05
Pretty sure this one's a duplicate of #209

**Closed by jbaicoianu** 2021-11-03 23:05 UTC
