### ISSUE TITLE
Teleporter not working in latest version

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#142] opened 2018-05-15 07:29 UTC
Made a test room for fixing teleporter.js, here's a version where it worked really great
https://web.janusvr.com/1.1.9/sites/https://vesta.janusvr.com/bepis/teleporter-test

I'm using the script hosted at https://www.metacade.com/traversal/teleporter.js, and it broke after janusweb version 1.1.10.

**Comment by jbaicoianu** [comment] 2018-05-16 22:51
Duplicate of #122

**Closed by jbaicoianu** 2018-05-16 22:51 UTC
