### ISSUE TITLE
I have an object where janusweb will not render the second .gif texture.

### ISSUE THREAD

**Issue by scooterboo** [jbaicoianu/janusweb#109] opened 2018-01-11 02:59 UTC
On the ground in https://nazrin.net/Date/ , the texture that is supposed to be https://nazrin.net/Date/waves1.gif gets replaced with https://nazrin.net/Date/waves2.gif , and the texture that is supposed to be https://nazrin.net/Date/waves2.gif is transparent.

**Comment by jbaicoianu** [comment] 2018-04-18 06:09
I believe this is fixed in 1.2 - could I get you to verify that https://web.janusvr.com/1.2/sites/https/nazrin.net/Date/ looks as intended now?

**Closed** 2018-05-16 22:55 UTC
Labels: bug
