### ISSUE TITLE
Videos don't play as of 1.5(.2?)

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#178] opened 2020-01-19 00:07 UTC

**Comment by jbaicoianu** [comment] 2020-01-19 02:52
I think this is related to the thumbnail support added in the last release, I'll look into it

**Comment by jbaicoianu** [comment] 2020-04-04 09:36
I believe this is fixed now, if you could verify with 1.5.6, and please feel free to reopen if the issue persists, with a link to a room that doesn't work as intended

**Closed by jbaicoianu** 2020-04-04 09:36 UTC
Labels: bug
