### ISSUE TITLE
Transparent webm not working

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#170] opened 2019-07-27 20:57 UTC
Here are a couple test sites:

- https://vesta.janusvr.com/bepis/coral-miku2 (transparent webm not working)
- https://vesta.janusvr.com/bepis/white-grid   (sbs3d transparent webm not working)

**Comment by jbaicoianu** [comment] 2019-10-18 00:33
Duplicate of #177

**Closed by jbaicoianu** 2019-10-18 00:33 UTC
